# Learn more about configuring your extension at https://shopify.dev/docs/apps/app-extensions/configuration

name = "delivery-map-block"

uid = "6377a0a6-827c-1172-d615-f9a6a4807936c44686f5"

type = "theme"
api_version = "2026-01"

[build]
automatically_update_urls_on_dev = true

